steel.d("components/bluev/payinfo/tpl", ["tpl/runtime"],function(require, exports, module) {
var jade = require('tpl/runtime');
var undefined = void 0;
module.exports = function template(locals) {
var jade_debug = [{ lineno: 1, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (dapart, step) {
jade_debug.unshift({ lineno: 0, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
jade_debug.unshift({ lineno: 1, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"protocol_content\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 0, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
jade_debug.unshift({ lineno: 1, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/top_position.jade" });
buf.push("<p class=\"top_position\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 2, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/top_position.jade" });
buf.push("<a href=\"http://verified.weibo.com/verify\" target=\"_blank\" class=\"W_f14 varifyindex\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 2, filename: jade_debug[0].filename });
buf.push("认证首页");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.unshift({ lineno: 3, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/top_position.jade" });
buf.push("<span class=\"W_f14\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 3, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 4, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/top_position.jade" });
if(dapart == "enterprise")
{
jade_debug.unshift({ lineno: 5, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/top_position.jade" });
jade_debug.unshift({ lineno: 5, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/top_position.jade" });
buf.push(">企业认证");
jade_debug.shift();
jade_debug.shift();
}
else if(dapart = "group")
{
jade_debug.unshift({ lineno: 7, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/top_position.jade" });
jade_debug.unshift({ lineno: 7, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/top_position.jade" });
buf.push(">机构认证");
jade_debug.shift();
jade_debug.shift();
}
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 8, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/top_position.jade" });
buf.push("<a href=\"http://help.weibo.com/newtopic/e\" target=\"_blank\" class=\"W_fr\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: jade_debug[0].filename });
buf.push("认证帮助»");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift({ lineno: 0, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
jade_debug.unshift({ lineno: 1, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<div class=\"verifyNav clearfix\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 2, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
if (step == "1")
{
jade_debug.unshift({ lineno: 3, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
jade_debug.unshift({ lineno: 3, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<ul>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"first cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("1");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 6, filename: jade_debug[0].filename });
buf.push("同意协议");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"second\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: jade_debug[0].filename });
buf.push("2");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("确认展示信息");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 10, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"third\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 11, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 11, filename: jade_debug[0].filename });
buf.push("3 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 12, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 12, filename: jade_debug[0].filename });
buf.push("填写资料");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 13, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"fourth\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 14, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 14, filename: jade_debug[0].filename });
buf.push("4 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 15, filename: jade_debug[0].filename });
buf.push("信息确认");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 16, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"fifth\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 17, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 17, filename: jade_debug[0].filename });
buf.push("5 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 18, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 18, filename: jade_debug[0].filename });
buf.push("支付费用");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 19, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"sixth\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 20, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 20, filename: jade_debug[0].filename });
buf.push("6 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 21, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 21, filename: jade_debug[0].filename });
buf.push("等待审核");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
}
jade_debug.shift();
jade_debug.unshift({ lineno: 22, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
if (step == "2")
{
jade_debug.unshift({ lineno: 23, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
jade_debug.unshift({ lineno: 23, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<ul>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 24, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"first cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 24, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 25, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 25, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 26, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 26, filename: jade_debug[0].filename });
buf.push("B ");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 27, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 27, filename: jade_debug[0].filename });
buf.push("同意协议");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 28, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"second cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 29, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 29, filename: jade_debug[0].filename });
buf.push("2");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 30, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 30, filename: jade_debug[0].filename });
buf.push("确认展示信息");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 31, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"third\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 32, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 32, filename: jade_debug[0].filename });
buf.push("3 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 33, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 33, filename: jade_debug[0].filename });
buf.push("填写资料");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 34, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"fourth\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 35, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 35, filename: jade_debug[0].filename });
buf.push("4 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 36, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 36, filename: jade_debug[0].filename });
buf.push("信息确认");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 37, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"fifth\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 38, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 38, filename: jade_debug[0].filename });
buf.push("5 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 39, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 39, filename: jade_debug[0].filename });
buf.push("支付费用");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 40, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"sixth\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 41, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 41, filename: jade_debug[0].filename });
buf.push("6 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 42, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 42, filename: jade_debug[0].filename });
buf.push("等待审核\t\t");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
}
jade_debug.shift();
jade_debug.unshift({ lineno: 43, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
if (step == "3")
{
jade_debug.unshift({ lineno: 44, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
jade_debug.unshift({ lineno: 44, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<ul>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 45, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"first cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 45, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 46, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 46, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 47, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 47, filename: jade_debug[0].filename });
buf.push("B ");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 48, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 48, filename: jade_debug[0].filename });
buf.push("同意协议");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 49, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"second cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 50, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 51, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 51, filename: jade_debug[0].filename });
buf.push("B ");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 52, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 52, filename: jade_debug[0].filename });
buf.push("确认展示信息");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 53, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"third cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 53, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 54, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 54, filename: jade_debug[0].filename });
buf.push("3");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 55, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 55, filename: jade_debug[0].filename });
buf.push("填写资料");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 56, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"fourth\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 57, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 57, filename: jade_debug[0].filename });
buf.push("4 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 58, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 58, filename: jade_debug[0].filename });
buf.push("信息确认");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 59, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"fifth\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 60, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 60, filename: jade_debug[0].filename });
buf.push("5 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 61, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 61, filename: jade_debug[0].filename });
buf.push("支付费用");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 62, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"sixth\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 63, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 63, filename: jade_debug[0].filename });
buf.push("6 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 64, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 64, filename: jade_debug[0].filename });
buf.push("等待审核");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
}
jade_debug.shift();
jade_debug.unshift({ lineno: 65, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
if (step == "4")
{
jade_debug.unshift({ lineno: 66, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
jade_debug.unshift({ lineno: 66, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<ul>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 67, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"first cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 67, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 68, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 68, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 69, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 69, filename: jade_debug[0].filename });
buf.push("B ");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 70, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 70, filename: jade_debug[0].filename });
buf.push("同意协议");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 71, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"second cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 72, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 73, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 73, filename: jade_debug[0].filename });
buf.push("B ");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 74, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 74, filename: jade_debug[0].filename });
buf.push("确认展示信息");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 75, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"third cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 75, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 76, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 77, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 77, filename: jade_debug[0].filename });
buf.push("B ");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 78, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 78, filename: jade_debug[0].filename });
buf.push("填写资料");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 79, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"fourth cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 80, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 80, filename: jade_debug[0].filename });
buf.push("4 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 81, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 81, filename: jade_debug[0].filename });
buf.push("信息确认");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 82, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"fifth\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 83, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 83, filename: jade_debug[0].filename });
buf.push("5 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 84, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 84, filename: jade_debug[0].filename });
buf.push("支付费用");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 85, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"sixth\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 86, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 86, filename: jade_debug[0].filename });
buf.push("6 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 87, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 87, filename: jade_debug[0].filename });
buf.push("等待审核");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
}
jade_debug.shift();
jade_debug.unshift({ lineno: 88, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
if (step == "5")
{
jade_debug.unshift({ lineno: 89, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
jade_debug.unshift({ lineno: 89, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<ul>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 90, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"first cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 90, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 91, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 91, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 92, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 92, filename: jade_debug[0].filename });
buf.push("B ");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 93, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 93, filename: jade_debug[0].filename });
buf.push("同意协议");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 94, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"second cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 95, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 96, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 96, filename: jade_debug[0].filename });
buf.push("B ");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 97, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 97, filename: jade_debug[0].filename });
buf.push("确认展示信息");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 98, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"third cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 98, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 99, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 100, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 100, filename: jade_debug[0].filename });
buf.push("B ");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 101, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 101, filename: jade_debug[0].filename });
buf.push("填写资料");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 102, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"fourth cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 103, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 104, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 104, filename: jade_debug[0].filename });
buf.push("B");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 105, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 105, filename: jade_debug[0].filename });
buf.push("信息确认");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 106, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"fifth cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 107, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 107, filename: jade_debug[0].filename });
buf.push("5 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 108, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 108, filename: jade_debug[0].filename });
buf.push("支付费用");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 109, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"sixth\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 110, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 110, filename: jade_debug[0].filename });
buf.push("6 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 111, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 111, filename: jade_debug[0].filename });
buf.push("等待审核");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
}
jade_debug.shift();
jade_debug.unshift({ lineno: 112, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
if (step == "6")
{
jade_debug.unshift({ lineno: 113, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
jade_debug.unshift({ lineno: 113, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<ul>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 114, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"first cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 114, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 115, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 115, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 116, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 116, filename: jade_debug[0].filename });
buf.push("B ");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 117, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 117, filename: jade_debug[0].filename });
buf.push("同意协议");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 118, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"second cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 119, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 120, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 120, filename: jade_debug[0].filename });
buf.push("B ");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 121, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 121, filename: jade_debug[0].filename });
buf.push("确认展示信息");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 122, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"third cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 122, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 123, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 124, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 124, filename: jade_debug[0].filename });
buf.push("B ");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 125, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 125, filename: jade_debug[0].filename });
buf.push("填写资料");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 126, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"fourth cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 127, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 128, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 128, filename: jade_debug[0].filename });
buf.push("B");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 129, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 129, filename: jade_debug[0].filename });
buf.push("信息确认");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 130, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"fifth cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 131, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 132, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<em class=\"W_ficon ficon_correct S_ficon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 132, filename: jade_debug[0].filename });
buf.push("B");
jade_debug.shift();
jade_debug.shift();
buf.push("</em>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 133, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 133, filename: jade_debug[0].filename });
buf.push("支付费用");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 134, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<li class=\"sixth cur\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 135, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"step\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 135, filename: jade_debug[0].filename });
buf.push("6 ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 136, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/common/verifyNav/tpl.jade" });
buf.push("<span class=\"info\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 136, filename: jade_debug[0].filename });
buf.push("等待审核");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
}
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift({ lineno: 4, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"payinfo\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 5, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"item\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 6, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"dt\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 6, filename: jade_debug[0].filename });
buf.push("基础包");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"dd\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: jade_debug[0].filename });
buf.push("¥300/年");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"item\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 10, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"dt\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 10, filename: jade_debug[0].filename });
buf.push("权益扩展包");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 11, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"dd\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 12, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<span node-type=\"op1\" class=\"option sel\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 13, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<i class=\"icon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</i>");
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("¥5000/年");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<span node-type=\"op2\" class=\"option\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 16, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<i class=\"icon\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</i>");
jade_debug.shift();
jade_debug.unshift({ lineno: 17, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("¥9800/年");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 18, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"item\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 19, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"dt\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("总计");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 20, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"dd\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 21, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<span node-type=\"price\" class=\"price\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 21, filename: jade_debug[0].filename });
buf.push("¥5000/年");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 22, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<del node-type=\"original\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 22, filename: jade_debug[0].filename });
buf.push("¥5300/年");
jade_debug.shift();
jade_debug.shift();
buf.push("</del>");
jade_debug.shift();
jade_debug.unshift({ lineno: 23, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<span node-type=\"notice\" class=\"notice\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 23, filename: jade_debug[0].filename });
buf.push("返2000现金红包");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 24, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"optBtn\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 25, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<a href=\"javascript:window.history.back()\" class=\"W_btn_b\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 25, filename: jade_debug[0].filename });
buf.push("上一步");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.unshift({ lineno: 26, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<a node-type=\"payBtn\" href=\"#\" class=\"W_btn_a\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 26, filename: jade_debug[0].filename });
buf.push("去支付");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 27, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"intro clearfix\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 28, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"item\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 29, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<img node-type=\"item01\" src=\"http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 30, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"title\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 30, filename: jade_debug[0].filename });
buf.push("广告主功能");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 31, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 31, filename: jade_debug[0].filename });
buf.push("可以使用微博强大的微博推广功能");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 32, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"item\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 33, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<img node-type=\"item02\" src=\"http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 34, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"title\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 34, filename: jade_debug[0].filename });
buf.push("帐号资质审核服务");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 35, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 35, filename: jade_debug[0].filename });
buf.push("认证审核服务");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 36, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"item\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 37, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<img node-type=\"item03\" src=\"http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 38, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"title\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 38, filename: jade_debug[0].filename });
buf.push("微分析无限制");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 39, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 39, filename: jade_debug[0].filename });
buf.push("微分析无限制免费3条");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 40, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"item\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 41, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<img node-type=\"item04\" src=\"http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 42, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"title\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 42, filename: jade_debug[0].filename });
buf.push("抽奖、活动、卡券、粉丝服务平台增值功能");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 43, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 43, filename: jade_debug[0].filename });
buf.push("微博营销工具");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 44, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"item\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 45, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<img node-type=\"item05\" src=\"http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 46, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"title\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 46, filename: jade_debug[0].filename });
buf.push("品牌话题长期");
jade_debug.shift();
jade_debug.unshift({ lineno: 47, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<br/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 48, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("主持人");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 49, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 49, filename: jade_debug[0].filename });
buf.push("1个");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 50, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"item\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 51, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<img node-type=\"item06\" src=\"http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 52, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"title\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 52, filename: jade_debug[0].filename });
buf.push("企业用户客服");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 53, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 53, filename: jade_debug[0].filename });
buf.push("专业的企业客服");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 54, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"item\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 55, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<img node-type=\"item07\" src=\"http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 56, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"title\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 56, filename: jade_debug[0].filename });
buf.push("舆情产品30天免费");
jade_debug.shift();
jade_debug.unshift({ lineno: 57, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<br/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 58, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("试用");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 59, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 59, filename: jade_debug[0].filename });
buf.push("掌握舆论主动权");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 60, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"item\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 61, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<img node-type=\"item08\" src=\"http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 62, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"title\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 62, filename: jade_debug[0].filename });
buf.push("企业用户1对1");
jade_debug.shift();
jade_debug.unshift({ lineno: 63, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<br/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 64, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("高级客服");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 65, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 65, filename: jade_debug[0].filename });
buf.push("1对1客服快速解决问题");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 66, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"item\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 67, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<img node-type=\"item09\" src=\"http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 68, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"title\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 68, filename: jade_debug[0].filename });
buf.push("新产品优先体验及");
jade_debug.shift();
jade_debug.unshift({ lineno: 69, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<br/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 70, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("联合推广");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 71, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 71, filename: jade_debug[0].filename });
buf.push("优先享用最新的功能");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 72, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"item\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 73, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<img node-type=\"item10\" src=\"http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 74, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<div class=\"title\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 74, filename: jade_debug[0].filename });
buf.push("年运营数据分析报告");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 75, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 75, filename: jade_debug[0].filename });
buf.push("全方位掌握详细");
jade_debug.shift();
jade_debug.unshift({ lineno: 76, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("<br/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 77, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/components/bluev/payinfo/tpl.jade" });
buf.push("运营数据");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();}.call(this,"dapart" in locals_for_with?locals_for_with.dapart:typeof dapart!=="undefined"?dapart:undefined,"step" in locals_for_with?locals_for_with.step:typeof step!=="undefined"?step:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, ".protocol_content\n\tinclude ../common/top_position\n\tinclude ../common/verifyNav/tpl\n\t.payinfo\n\t\t.item\n\t\t\t.dt 基础包\n\t\t\t.dd\n\t\t\t\tspan ¥300/年\n\t\t.item\n\t\t\t.dt 权益扩展包\n\t\t\t.dd\n\t\t\t\tspan.option.sel(node-type='op1')\n\t\t\t\t\ti.icon\n\t\t\t\t\t| ¥5000/年\n\t\t\t\tspan.option(node-type='op2')\n\t\t\t\t\ti.icon\n\t\t\t\t\t| ¥9800/年\n\t\t.item\n\t\t\t.dt 总计\n\t\t\t.dd\n\t\t\t\tspan.price(node-type='price') ¥5000/年\n\t\t\t\tdel(node-type='original') ¥5300/年\n\t\t\t\tspan.notice(node-type='notice') 返2000现金红包\n\t\t.optBtn\n\t\t\ta.W_btn_b(href='javascript:window.history.back()') 上一步\n\t\t\ta.W_btn_a(node-type='payBtn' href='#') 去支付\n\t.intro.clearfix\n\t\t.item\n\t\t\timg(node-type='item01' src='http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png')\n\t\t\t.title 广告主功能\n\t\t\tp 可以使用微博强大的微博推广功能\n\t\t.item\n\t\t\timg(node-type='item02' src='http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png')\n\t\t\t.title 帐号资质审核服务\n\t\t\tp 认证审核服务\n\t\t.item\n\t\t\timg(node-type='item03' src='http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png')\n\t\t\t.title 微分析无限制\n\t\t\tp 微分析无限制免费3条\n\t\t.item\n\t\t\timg(node-type='item04' src='http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png')\n\t\t\t.title 抽奖、活动、卡券、粉丝服务平台增值功能\n\t\t\tp 微博营销工具\n\t\t.item\n\t\t\timg(node-type='item05' src='http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png')\n\t\t\t.title 品牌话题长期\n\t\t\t\tbr\n\t\t\t\t| 主持人\n\t\t\tp 1个\n\t\t.item\n\t\t\timg(node-type='item06' src='http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png')\n\t\t\t.title 企业用户客服\n\t\t\tp 专业的企业客服\n\t\t.item\n\t\t\timg(node-type='item07' src='http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png')\n\t\t\t.title 舆情产品30天免费\n\t\t\t\tbr\n\t\t\t\t| 试用\n\t\t\tp 掌握舆论主动权\n\t\t.item\n\t\t\timg(node-type='item08' src='http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png')\n\t\t\t.title 企业用户1对1\n\t\t\t\tbr\n\t\t\t\t| 高级客服\n\t\t\tp 1对1客服快速解决问题\n\t\t.item\n\t\t\timg(node-type='item09' src='http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png')\n\t\t\t.title 新产品优先体验及\n\t\t\t\tbr\n\t\t\t\t| 联合推广\n\t\t\tp 优先享用最新的功能\n\t\t.item\n\t\t\timg(node-type='item10' src='http://img.t.sinajs.cn/t6/business/src/css/bluev/img/temp01.png')\n\t\t\t.title 年运营数据分析报告\n\t\t\tp 全方位掌握详细\n\t\t\t\tbr\n\t\t\t\t| 运营数据");
}
};
});