steel.d("common/loading/tpl", ["tpl/runtime"],function(require, exports, module) {
var jade = require('tpl/runtime');
var undefined = void 0;
module.exports = function template(locals) {
var jade_debug = [{ lineno: 1, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;

jade_debug.unshift({ lineno: 0, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.unshift({ lineno: 1, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
buf.push("<div style=\"height:300px;\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 3, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
buf.push("<div class=\"E_loading\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
buf.push("<div class=\"loading_cont W_tc\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 5, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
buf.push("<p class=\"icon_bed E_MB10\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 6, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
buf.push("<i class=\"W_loading_big\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</i>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
buf.push("<p class=\"S_txt2\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 7, filename: jade_debug[0].filename });
buf.push("加载中，请稍候 ...");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 8, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
buf.push("");
jade_debug.shift();
jade_debug.unshift({ lineno: 10, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 11, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 12, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 13, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 16, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 17, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 18, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 19, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 20, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 21, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 22, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 23, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 24, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 25, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 26, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 27, filename: "/Users/lihan/Documents/projects/js.wcdn.cn/t6/steelProj/src/common/loading/tpl.jade" });
jade_debug.shift();
jade_debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "//- 主站统一loading结构 start --------------\ndiv(style='height:300px;')\n    .E_loading\n        .loading_cont.W_tc\n            p.icon_bed.E_MB10\n                i.W_loading_big\n            p.S_txt2 加载中，请稍候 ...\n//- 主站统一loading结构 end --------------\n\n//------------ css3 结构 start-----------------------------------\n//- .webapp_spinner\n//-     .webapp_spinner-container.webapp_container1\n//-         .webapp_circle1\n//-         .webapp_circle2\n//-         .webapp_circle3\n//-         .webapp_circle4\n//-     .webapp_spinner-container.webapp_container2\n//-         .webapp_circle1\n//-         .webapp_circle2\n//-         .webapp_circle3\n//-         .webapp_circle4\n//-     .spinner-container.container3\n//-         .webapp_circle1\n//-         .webapp_circle2\n//-         .webapp_circle3\n//-         .webapp_circle4\n//------------ css3 结构 end-----------------------------------\n");
}
};
});