<!DOCTYPE html>
<html lang="en">
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
  <title>群发私信</title>
  <link rel="stylesheet" href="http://img.t.sinajs.cn/t4/appstyle/e/apps/message/css/mobile_base.css?version=<?= htmlentities($g_version_css, ENT_QUOTES, 'UTF-8') ?>" />
  <script src="http://js.t.sinajs.cn/t6/apps/fans_service_mobile/js/lib/lib.js?version=<?= htmlentities($g_version_css, ENT_QUOTES, 'UTF-8') ?>"></script>
  <script src="http://js.t.sinajs.cn/t6/apps/fans_service_mobile/js/app/groupmsg.js?version=<?= htmlentities($g_version_css, ENT_QUOTES, 'UTF-8') ?>"></script>
  <?php include(dirname(__FILE__) . '/../../common/include/config.phtml') ?>
  <script>steel.boot('app/groupmsg');</script>
 </head>
 <body></body>
</html>